/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.lettersandnumbers.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.lettersandnumbers.block.*;
import net.mcreator.lettersandnumbers.LettersAndNumbersMod;

public class LettersAndNumbersModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, LettersAndNumbersMod.MODID);
	public static final RegistryObject<Block> A_BLOCK;
	public static final RegistryObject<Block> A_BLOCK_GREEN;
	public static final RegistryObject<Block> A_BLOCK_YELLOW;
	public static final RegistryObject<Block> B_BLOCK_GREEN;
	public static final RegistryObject<Block> B_BLOCK_YELLOW;
	public static final RegistryObject<Block> B_BLOCK;
	public static final RegistryObject<Block> C_BLOCK;
	public static final RegistryObject<Block> C_BLOCK_YELLOW;
	public static final RegistryObject<Block> C_BLOCK_GREEN;
	public static final RegistryObject<Block> LETTERSANDNUMBERSCMICO;
	public static final RegistryObject<Block> D_BLOCK;
	public static final RegistryObject<Block> D_BLOCK_YELLOW;
	public static final RegistryObject<Block> D_BLOCK_GREEN;
	public static final RegistryObject<Block> E_BLOCK_YELLOW;
	public static final RegistryObject<Block> E_BLOCK_GREEN;
	public static final RegistryObject<Block> E_BLOCK;
	public static final RegistryObject<Block> FBLOCK_GREEN;
	public static final RegistryObject<Block> F_BLOCK_YELLOW;
	public static final RegistryObject<Block> F_BLOCK;
	public static final RegistryObject<Block> G_BLOCK_YELLOW;
	public static final RegistryObject<Block> G_BLOCK_GREEN;
	public static final RegistryObject<Block> G_BLOCK;
	public static final RegistryObject<Block> H_BLOCK_YELLOW;
	public static final RegistryObject<Block> H_BLOCK_GREEN;
	public static final RegistryObject<Block> H_BLOCK;
	public static final RegistryObject<Block> I_BLOCK_YELLOW;
	public static final RegistryObject<Block> I_BLOCK_GREEN;
	public static final RegistryObject<Block> I_BLOCK;
	public static final RegistryObject<Block> J_BLOCK_GREEN;
	public static final RegistryObject<Block> J_BLOCK_YELLOW;
	public static final RegistryObject<Block> J_BLOCK;
	public static final RegistryObject<Block> K_BLOCK_GREEN;
	public static final RegistryObject<Block> K_BLOCK_YELLOW;
	public static final RegistryObject<Block> K_BLOCK;
	public static final RegistryObject<Block> L_BLOCK_GREEN;
	public static final RegistryObject<Block> L_BLOCK_YELLOW;
	public static final RegistryObject<Block> L_BLOCK;
	public static final RegistryObject<Block> M_BLOCK_GREEN;
	public static final RegistryObject<Block> M_BLOCK_YELLOW;
	public static final RegistryObject<Block> M_BLOCK;
	public static final RegistryObject<Block> N_BLOCK_GREEN;
	public static final RegistryObject<Block> N_BLOCK_YELLOW;
	public static final RegistryObject<Block> N_BLOCK;
	public static final RegistryObject<Block> O_BLOCK_GREEN;
	public static final RegistryObject<Block> O_BLOCK_YELLOW;
	public static final RegistryObject<Block> O_BLOCK;
	public static final RegistryObject<Block> P_BLOCK_GREEN;
	public static final RegistryObject<Block> P_BLOCK_YELLOW;
	public static final RegistryObject<Block> P_BLOCK;
	public static final RegistryObject<Block> Q_BLOCK_GREEN;
	public static final RegistryObject<Block> Q_BLOCK_YELLOW;
	public static final RegistryObject<Block> Q_BLOCK;
	public static final RegistryObject<Block> R_BLOCK_GREEN;
	public static final RegistryObject<Block> R_BLOCK_YELLOW;
	public static final RegistryObject<Block> R_BLOCK;
	public static final RegistryObject<Block> S_BLOCK_GREEN;
	public static final RegistryObject<Block> S_BLOCK_YELLOW;
	public static final RegistryObject<Block> S_BLOCK;
	public static final RegistryObject<Block> T_BLOCK_GREEN;
	public static final RegistryObject<Block> T_BLOCK_YELLOW;
	public static final RegistryObject<Block> T_BLOCK;
	public static final RegistryObject<Block> U_BLOCK_GREEN;
	public static final RegistryObject<Block> U_BLOCK_YELLOW;
	public static final RegistryObject<Block> U_BLOCK;
	public static final RegistryObject<Block> V_BLOCK_GREEN;
	public static final RegistryObject<Block> V_BLOCK_YELLOW;
	public static final RegistryObject<Block> V_BLOCK;
	public static final RegistryObject<Block> W_BLOCK_GREEN;
	public static final RegistryObject<Block> W_BLOCK_YELLOW;
	public static final RegistryObject<Block> W_BLOCK;
	public static final RegistryObject<Block> X_BLOCK_GREEN;
	public static final RegistryObject<Block> X_BLOCK_YELLOW;
	public static final RegistryObject<Block> X_BLOCK;
	public static final RegistryObject<Block> Y_BLOCK_GREEN;
	public static final RegistryObject<Block> Y_BLOCK_YELLOW;
	public static final RegistryObject<Block> Y_BLOCK;
	public static final RegistryObject<Block> Z_BLOCK_GREEN;
	public static final RegistryObject<Block> Z_BLOCK_YELLOW;
	public static final RegistryObject<Block> Z_BLOCK;
	static {
		A_BLOCK = REGISTRY.register("a_block", ABlockBlock::new);
		A_BLOCK_GREEN = REGISTRY.register("a_block_green", ABlockGreenBlock::new);
		A_BLOCK_YELLOW = REGISTRY.register("a_block_yellow", ABlockYellowBlock::new);
		B_BLOCK_GREEN = REGISTRY.register("b_block_green", BBlockGreenBlock::new);
		B_BLOCK_YELLOW = REGISTRY.register("b_block_yellow", BBlockYellowBlock::new);
		B_BLOCK = REGISTRY.register("b_block", BBlockBlock::new);
		C_BLOCK = REGISTRY.register("c_block", CBlockBlock::new);
		C_BLOCK_YELLOW = REGISTRY.register("c_block_yellow", CBlockYellowBlock::new);
		C_BLOCK_GREEN = REGISTRY.register("c_block_green", CBlockGreenBlock::new);
		LETTERSANDNUMBERSCMICO = REGISTRY.register("lettersandnumberscmico", LettersandnumberscmicoBlock::new);
		D_BLOCK = REGISTRY.register("d_block", DBlockBlock::new);
		D_BLOCK_YELLOW = REGISTRY.register("d_block_yellow", DBlockYellowBlock::new);
		D_BLOCK_GREEN = REGISTRY.register("d_block_green", DBlockGreenBlock::new);
		E_BLOCK_YELLOW = REGISTRY.register("e_block_yellow", EBlockYellowBlock::new);
		E_BLOCK_GREEN = REGISTRY.register("e_block_green", EBlockGreenBlock::new);
		E_BLOCK = REGISTRY.register("e_block", EBlockBlock::new);
		FBLOCK_GREEN = REGISTRY.register("fblock_green", FblockGreenBlock::new);
		F_BLOCK_YELLOW = REGISTRY.register("f_block_yellow", FBlockYellowBlock::new);
		F_BLOCK = REGISTRY.register("f_block", FBlockBlock::new);
		G_BLOCK_YELLOW = REGISTRY.register("g_block_yellow", GBlockYellowBlock::new);
		G_BLOCK_GREEN = REGISTRY.register("g_block_green", GBlockGreenBlock::new);
		G_BLOCK = REGISTRY.register("g_block", GBlockBlock::new);
		H_BLOCK_YELLOW = REGISTRY.register("h_block_yellow", HBlockYellowBlock::new);
		H_BLOCK_GREEN = REGISTRY.register("h_block_green", HBlockGreenBlock::new);
		H_BLOCK = REGISTRY.register("h_block", HBlockBlock::new);
		I_BLOCK_YELLOW = REGISTRY.register("i_block_yellow", IBlockYellowBlock::new);
		I_BLOCK_GREEN = REGISTRY.register("i_block_green", IBlockGreenBlock::new);
		I_BLOCK = REGISTRY.register("i_block", IBlockBlock::new);
		J_BLOCK_GREEN = REGISTRY.register("j_block_green", JBlockGreenBlock::new);
		J_BLOCK_YELLOW = REGISTRY.register("j_block_yellow", JBlockYellowBlock::new);
		J_BLOCK = REGISTRY.register("j_block", JBlockBlock::new);
		K_BLOCK_GREEN = REGISTRY.register("k_block_green", KBlockGreenBlock::new);
		K_BLOCK_YELLOW = REGISTRY.register("k_block_yellow", KBlockYellowBlock::new);
		K_BLOCK = REGISTRY.register("k_block", KBlockBlock::new);
		L_BLOCK_GREEN = REGISTRY.register("l_block_green", LBlockGreenBlock::new);
		L_BLOCK_YELLOW = REGISTRY.register("l_block_yellow", LBlockYellowBlock::new);
		L_BLOCK = REGISTRY.register("l_block", LBlockBlock::new);
		M_BLOCK_GREEN = REGISTRY.register("m_block_green", MBlockGreenBlock::new);
		M_BLOCK_YELLOW = REGISTRY.register("m_block_yellow", MBlockYellowBlock::new);
		M_BLOCK = REGISTRY.register("m_block", MBlockBlock::new);
		N_BLOCK_GREEN = REGISTRY.register("n_block_green", NBlockGreenBlock::new);
		N_BLOCK_YELLOW = REGISTRY.register("n_block_yellow", NBlockYellowBlock::new);
		N_BLOCK = REGISTRY.register("n_block", NBlockBlock::new);
		O_BLOCK_GREEN = REGISTRY.register("o_block_green", OBlockGreenBlock::new);
		O_BLOCK_YELLOW = REGISTRY.register("o_block_yellow", OBlockYellowBlock::new);
		O_BLOCK = REGISTRY.register("o_block", OBlockBlock::new);
		P_BLOCK_GREEN = REGISTRY.register("p_block_green", PBlockGreenBlock::new);
		P_BLOCK_YELLOW = REGISTRY.register("p_block_yellow", PBlockYellowBlock::new);
		P_BLOCK = REGISTRY.register("p_block", PBlockBlock::new);
		Q_BLOCK_GREEN = REGISTRY.register("q_block_green", QBlockGreenBlock::new);
		Q_BLOCK_YELLOW = REGISTRY.register("q_block_yellow", QBlockYellowBlock::new);
		Q_BLOCK = REGISTRY.register("q_block", QBlockBlock::new);
		R_BLOCK_GREEN = REGISTRY.register("r_block_green", RBlockGreenBlock::new);
		R_BLOCK_YELLOW = REGISTRY.register("r_block_yellow", RBlockYellowBlock::new);
		R_BLOCK = REGISTRY.register("r_block", RBlockBlock::new);
		S_BLOCK_GREEN = REGISTRY.register("s_block_green", SBlockGreenBlock::new);
		S_BLOCK_YELLOW = REGISTRY.register("s_block_yellow", SBlockYellowBlock::new);
		S_BLOCK = REGISTRY.register("s_block", SBlockBlock::new);
		T_BLOCK_GREEN = REGISTRY.register("t_block_green", TBlockGreenBlock::new);
		T_BLOCK_YELLOW = REGISTRY.register("t_block_yellow", TBlockYellowBlock::new);
		T_BLOCK = REGISTRY.register("t_block", TBlockBlock::new);
		U_BLOCK_GREEN = REGISTRY.register("u_block_green", UBlockGreenBlock::new);
		U_BLOCK_YELLOW = REGISTRY.register("u_block_yellow", UBlockYellowBlock::new);
		U_BLOCK = REGISTRY.register("u_block", UBlockBlock::new);
		V_BLOCK_GREEN = REGISTRY.register("v_block_green", VBlockGreenBlock::new);
		V_BLOCK_YELLOW = REGISTRY.register("v_block_yellow", VBlockYellowBlock::new);
		V_BLOCK = REGISTRY.register("v_block", VBlockBlock::new);
		W_BLOCK_GREEN = REGISTRY.register("w_block_green", WBlockGreenBlock::new);
		W_BLOCK_YELLOW = REGISTRY.register("w_block_yellow", WBlockYellowBlock::new);
		W_BLOCK = REGISTRY.register("w_block", WBlockBlock::new);
		X_BLOCK_GREEN = REGISTRY.register("x_block_green", XBlockGreenBlock::new);
		X_BLOCK_YELLOW = REGISTRY.register("x_block_yellow", XBlockYellowBlock::new);
		X_BLOCK = REGISTRY.register("x_block", XBlockBlock::new);
		Y_BLOCK_GREEN = REGISTRY.register("y_block_green", YBlockGreenBlock::new);
		Y_BLOCK_YELLOW = REGISTRY.register("y_block_yellow", YBlockYellowBlock::new);
		Y_BLOCK = REGISTRY.register("y_block", YBlockBlock::new);
		Z_BLOCK_GREEN = REGISTRY.register("z_block_green", ZBlockGreenBlock::new);
		Z_BLOCK_YELLOW = REGISTRY.register("z_block_yellow", ZBlockYellowBlock::new);
		Z_BLOCK = REGISTRY.register("z_block", ZBlockBlock::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}