modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="letters_and_numbers"
version="1.0.0"
displayName="Letters And Numbers"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.letters_and_numbers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration